# ==========================
#COMUN
# ==========================
spring.application.name=SMSFILTER
server.servlet.context-path=/sms-filter
spring.web.resources.static-locations=classpath:/static/,file:./data/static/

security.jwt.secret=SMS_FILTER_SECRETO_2026
security.jwt.expiration=600000

# ==========================
# PERFIL DEV
# ==========================

#CORS
app.cors.allowed-origins=http://localhost:4200,http://localhost:5173

# DATASOURCE
spring.datasource.url=jdbc:postgresql://localhost:5434/filtro-sms
spring.datasource.username=postgres
spring.datasource.password=123456

# HikariCP (solo aplica en dev, porque Spring crea el pool)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ==========================
# PERFIL PROD
# ==========================

#CORS
#app.cors.allowed-origins=https://www.comfenalcoantioquia.com.co,http://172.30.1.46,http://172.30.1.46:10103,http://192.168.1.15:10103,http://192.168.1.56:10103,http://localhost:4200,http://localhost:5173

# DATASOURCE JNDI (WAS)

#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# HikariCP (solo aplica en dev, porque Spring crea el pool)
#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.minimum-idle=2
#spring.datasource.hikari.connection-timeout=30000
#spring.datasource.hikari.validation-timeout=5000
#spring.datasource.hikari.idle-timeout=600000
#spring.datasource.hikari.max-lifetime=1800000

# JPA / HIBERNATE
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.open-in-view=false
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

